services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=${DB_NAME}'
      - 'MYSQL_PASSWORD=${DB_PASSWORD}'
      - 'MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}'
      - 'MYSQL_USER=${DB_USER}'
    ports:
      - '${DB_PORT}:3306'
    command:
      # Debezium을 위한 binlog 설정 (필수)
      - "--server-id=223344"
      - "--log-bin=mysql-bin"
      - "--binlog-format=ROW"
      - "--binlog-row-image=FULL"

  kafka-broker-1:
    image: confluentinc/cp-kafka:7.6.0
    ports:
      - "19092:19092"
    environment:
      # Kraft 모드 필수 설정
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_NODE_ID=1
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka-broker-1:29092,2@kafka-broker-2:29093,3@kafka-broker-3:29094
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      # 클러스터 ID
      - CLUSTER_ID=MkU3OEVBNTcwNTJENDM2Qk
      # 클라이언트에게 알릴 주소 설정
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-broker-1:9092,PLAINTEXT_HOST://localhost:19092
      # 브로커가 실제로 바인딩할 주소
      - KAFKA_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:19092,CONTROLLER://:29092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
  kafka-broker-2:
    image: confluentinc/cp-kafka:7.6.0
    ports:
      - "19093:19093"
    environment:
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_NODE_ID=2
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka-broker-1:29092,2@kafka-broker-2:29093,3@kafka-broker-3:29094
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - CLUSTER_ID=MkU3OEVBNTcwNTJENDM2Qk
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-broker-2:9092,PLAINTEXT_HOST://localhost:19093
      - KAFKA_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:19093,CONTROLLER://:29093
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
  kafka-broker-3:
    image: confluentinc/cp-kafka:7.6.0
    ports:
      - "19094:19094"
    environment:
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_NODE_ID=3
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka-broker-1:29092,2@kafka-broker-2:29093,3@kafka-broker-3:29094
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - CLUSTER_ID=MkU3OEVBNTcwNTJENDM2Qk
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-broker-3:9092,PLAINTEXT_HOST://localhost:19094
      - KAFKA_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:19094,CONTROLLER://:29094
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
  kafka-ui:
    image: provectuslabs/kafka-ui
    ports:
      - "8090:8080"
    environment:
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-broker-1:9092,kafka-broker-2:9092,kafka-broker-3:9092
      - KAFKA_CLUSTERS_0_NAME=ALLMart_test
    depends_on:
      - kafka-broker-1
      - kafka-broker-2
      - kafka-broker-3
  redis:
    image: 'redis:7-alpine'
    ports:
      - '6379:6379'

  debezium:
    image: debezium/connect:3.0.0.Final
    ports:
      - "8083:8083"
    environment:
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_source_connect_statuses
      - BOOTSTRAP_SERVERS=kafka-broker-1:9092,kafka-broker-2:9092,kafka-broker-3:9092
    depends_on:
      - kafka-broker-1
      - kafka-broker-2
      - kafka-broker-3
